#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults
# main bar & defaults
sketchybar --bar height=45        \
                 margin=20        \
                 y_offset=0       \
                 padding_left=0   \
                 padding_right=0  \
                 color=0x00000000 \
                 blur_radius=100	\
				 color="$TRANSPARENT" \

sketchybar --default updates=when_shown                             \
                     icon.font="Liga SFMono Nerd Font:Normal:14.0"  \
                     icon.color=0xFFFFFFFF                          \
                     label.font="Liga SFMono Nerd Font:Normal:14.0" \
                     background.color=0x00000000                    \
                     y_offset=0


# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center (of notch)
source "$ITEM_DIR/spotify.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true
sketchybar --update

echo "sketchybar configuration loaded.."
