#theme = "Zenburn"

[colors]

# name = "zenburn"

[colors.bright]
black = "#709080"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#c3bf9f"
magenta = "#ec93d3"
red = "#dca3a3"
white = "#ffffff"
yellow = "#f0dfaf"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#1e2320"
blue = "#506070"
cyan = "#8cd0d3"
green = "#60b48a"
magenta = "#dc8cc3"
red = "#705050"
white = "#dcdccc"
yellow = "#dfaf8f"

# [colors.primary]
# background = "#000000"
# foreground = "#ffffff"

[cursor]
style = "Beam"
thickness = 0.3


[window]
padding.x = 20
padding.y = 20

decorations = "none"
dynamic_padding = true

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Regular"

size = 16


# [terminal.shell
# program = "/opt/homebrew/bin/fish"
