#!bin/sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp
yabai -m config window_placement second_child

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding    20
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on

# yabai -m config active_window_opacity 1
yabai -m config normal_window_opacity 0.97

# yabai -m rule --add app="^Code$" opacity=0.1


# center mouse on window with focus
# yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off


yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus


# when window is dropped in center of another window, swap them (on edges it will split it)

yabai -m config external_bar all:30:0



# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus off